# Site settings
name: Muhammad Sufyan Shoaib
author: 'Muhammad Sufyan Shoaib'
title: Techie Stuff @ sufyanshoaib
email: sufyanshoaib[at]gmail.com
description: Technology stuffs, tutorials, articles, news etc
meta_description: "Technology stuffs, tutorials, articles, news etc"
url: "http://sufyanshoaib.com" # the base hostname & protocol for your site
twitter_username: sufyanshoaib
github_username:  sufyanshoaib

# Build settings
markdown: kramdown
